name: Docker Image CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_REPOSITORY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIETPI_IP }}
        username: ${{ secrets.DIETPI_USER }}
        password: ${{ secrets.DIETPI_PASSWORD }}
        port: 22
        script: |
          # Stop and remove old container
          docker stop my_container
          docker rm my_container

          # Pull new image
          docker pull ${{ secrets.DOCKER_HUB_REPOSITORY }}

          # Run new container
          docker run -d --name my_container ${{ secrets.DOCKER_HUB_REPOSITORY }}

