name: Docker Image CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKER_HUB_REPOSITORY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass curl
          curl -L https://github.com/cloudflare/cloudflared/releases/download/2023.7.3/cloudflared-linux-amd64 -o cloudflared
          sudo mv cloudflared /usr/bin/
          sudo chmod +x /usr/bin/cloudflared
          sudo mkdir -p /root/.ssh

      - name: Copy and set permissions for script
        run: |
          cp cloudflared_ssh.sh .github/
          chmod +x .github/cloudflared_ssh.sh

      - name: Cloudflared SSH Deploy
        env:
          DIETPI_IP: ${{ secrets.DIETPI_IP }}
          DIETPI_USER: ${{ secrets.DIETPI_USER }}
          DIETPI_PASSWORD: ${{ secrets.DIETPI_PASSWORD }}
          SSH_SCRIPT: |
            # Stop and remove old container
            docker stop my_container
            docker rm my_container

            # Pull new image
            docker pull ${{ secrets.DOCKER_HUB_REPOSITORY }}

            # Run new container
            docker run -d --name my_container -p 8080:8080 ${{ secrets.DOCKER_HUB_REPOSITORY }}
        run: |
          .github/cloudflared_ssh.sh $DIETPI_IP 22 $DIETPI_USER "$DIETPI_PASSWORD" "$SSH_SCRIPT"
